import { Pool } from "pg";

export async function seedGeoReference(pool: Pool) {
  const client = await pool.connect();
  try {
    await client.query("BEGIN");

    await client.query(`
      INSERT INTO countries (name, iso2, iso3, numeric_code, official_name, capital, region_hint)
      VALUES
        ('Afghanistan','AF','AFG',4,'Islamic Republic of Afghanistan','Kabul','Asia-Pacific'),
        ('Albania','AL','ALB',8,'Republic of Albania','Tirana','Europe'),
        ('Algeria','DZ','DZA',12,'People''s Democratic Republic of Algeria','Algiers','MENA'),
        ('Andorra','AD','AND',20,'Principality of Andorra','Andorra la Vella','Europe'),
        ('Angola','AO','AGO',24,'Republic of Angola','Luanda','SSA'),
        ('Antigua and Barbuda','AG','ATG',28,'Antigua and Barbuda','Saint John''s','Americas'),
        ('Argentina','AR','ARG',32,'Argentine Republic','Buenos Aires','Americas'),
        ('Armenia','AM','ARM',51,'Republic of Armenia','Yerevan','Europe'),
        ('Australia','AU','AUS',36,'Commonwealth of Australia','Canberra','Asia-Pacific'),
        ('Austria','AT','AUT',40,'Republic of Austria','Vienna','EU'),
        ('Azerbaijan','AZ','AZE',31,'Republic of Azerbaijan','Baku','Europe'),
        ('Bahamas','BS','BHS',44,'Commonwealth of The Bahamas','Nassau','Americas'),
        ('Bahrain','BH','BHR',48,'Kingdom of Bahrain','Manama','MENA'),
        ('Bangladesh','BD','BGD',50,'People''s Republic of Bangladesh','Dhaka','Asia-Pacific'),
        ('Barbados','BB','BRB',52,'Barbados','Bridgetown','Americas'),
        ('Belarus','BY','BLR',112,'Republic of Belarus','Minsk','Europe'),
        ('Belgium','BE','BEL',56,'Kingdom of Belgium','Brussels','EU'),
        ('Belize','BZ','BLZ',84,'Belize','Belmopan','Americas'),
        ('Benin','BJ','BEN',204,'Republic of Benin','Porto-Novo','SSA'),
        ('Bhutan','BT','BTN',64,'Kingdom of Bhutan','Thimphu','Asia-Pacific'),
        ('Bolivia','BO','BOL',68,'Plurinational State of Bolivia','Sucre','Americas'),
        ('Bosnia and Herzegovina','BA','BIH',70,'Bosnia and Herzegovina','Sarajevo','Europe'),
        ('Botswana','BW','BWA',72,'Republic of Botswana','Gaborone','SSA'),
        ('Brazil','BR','BRA',76,'Federative Republic of Brazil','Brasilia','Americas'),
        ('Brunei','BN','BRN',96,'Brunei Darussalam','Bandar Seri Begawan','Asia-Pacific'),
        ('Bulgaria','BG','BGR',100,'Republic of Bulgaria','Sofia','EU'),
        ('Burkina Faso','BF','BFA',854,'Burkina Faso','Ouagadougou','SSA'),
        ('Burundi','BI','BDI',108,'Republic of Burundi','Gitega','SSA'),
        ('Cabo Verde','CV','CPV',132,'Republic of Cabo Verde','Praia','SSA'),
        ('Cambodia','KH','KHM',116,'Kingdom of Cambodia','Phnom Penh','Asia-Pacific'),
        ('Cameroon','CM','CMR',120,'Republic of Cameroon','Yaounde','SSA'),
        ('Canada','CA','CAN',124,'Canada','Ottawa','Americas'),
        ('Central African Republic','CF','CAF',140,'Central African Republic','Bangui','SSA'),
        ('Chad','TD','TCD',148,'Republic of Chad','N''Djamena','SSA'),
        ('Chile','CL','CHL',152,'Republic of Chile','Santiago','Americas'),
        ('China','CN','CHN',156,'People''s Republic of China','Beijing','Asia-Pacific'),
        ('Colombia','CO','COL',170,'Republic of Colombia','Bogota','Americas'),
        ('Comoros','KM','COM',174,'Union of the Comoros','Moroni','SSA'),
        ('Congo (Republic)','CG','COG',178,'Republic of the Congo','Brazzaville','SSA'),
        ('Congo (DRC)','CD','COD',180,'Democratic Republic of the Congo','Kinshasa','SSA'),
        ('Costa Rica','CR','CRI',188,'Republic of Costa Rica','San Jose','Americas'),
        ('Croatia','HR','HRV',191,'Republic of Croatia','Zagreb','EU'),
        ('Cuba','CU','CUB',192,'Republic of Cuba','Havana','Americas'),
        ('Cyprus','CY','CYP',196,'Republic of Cyprus','Nicosia','EU'),
        ('Czech Republic','CZ','CZE',203,'Czech Republic','Prague','EU'),
        ('Denmark','DK','DNK',208,'Kingdom of Denmark','Copenhagen','EU'),
        ('Djibouti','DJ','DJI',262,'Republic of Djibouti','Djibouti','SSA'),
        ('Dominica','DM','DMA',212,'Commonwealth of Dominica','Roseau','Americas'),
        ('Dominican Republic','DO','DOM',214,'Dominican Republic','Santo Domingo','Americas'),
        ('Ecuador','EC','ECU',218,'Republic of Ecuador','Quito','Americas'),
        ('Egypt','EG','EGY',818,'Arab Republic of Egypt','Cairo','MENA'),
        ('El Salvador','SV','SLV',222,'Republic of El Salvador','San Salvador','Americas'),
        ('Equatorial Guinea','GQ','GNQ',226,'Republic of Equatorial Guinea','Malabo','SSA'),
        ('Eritrea','ER','ERI',232,'State of Eritrea','Asmara','SSA'),
        ('Estonia','EE','EST',233,'Republic of Estonia','Tallinn','EU'),
        ('Eswatini','SZ','SWZ',748,'Kingdom of Eswatini','Mbabane','SSA'),
        ('Ethiopia','ET','ETH',231,'Federal Democratic Republic of Ethiopia','Addis Ababa','SSA'),
        ('Fiji','FJ','FJI',242,'Republic of Fiji','Suva','Asia-Pacific'),
        ('Finland','FI','FIN',246,'Republic of Finland','Helsinki','EU'),
        ('France','FR','FRA',250,'French Republic','Paris','EU'),
        ('French Polynesia','PF','PYF',258,'French Polynesia','Papeete','Asia-Pacific'),
        ('Gabon','GA','GAB',266,'Gabonese Republic','Libreville','SSA'),
        ('Gambia','GM','GMB',270,'Republic of The Gambia','Banjul','SSA'),
        ('Georgia','GE','GEO',268,'Georgia','Tbilisi','Europe'),
        ('Germany','DE','DEU',276,'Federal Republic of Germany','Berlin','EU'),
        ('Ghana','GH','GHA',288,'Republic of Ghana','Accra','SSA'),
        ('Greece','GR','GRC',300,'Hellenic Republic','Athens','EU'),
        ('Grenada','GD','GRD',308,'Grenada','Saint George''s','Americas'),
        ('Guatemala','GT','GTM',320,'Republic of Guatemala','Guatemala City','Americas'),
        ('Guinea','GN','GIN',324,'Republic of Guinea','Conakry','SSA'),
        ('Guinea-Bissau','GW','GNB',624,'Republic of Guinea-Bissau','Bissau','SSA'),
        ('Guyana','GY','GUY',328,'Co-operative Republic of Guyana','Georgetown','Americas'),
        ('Haiti','HT','HTI',332,'Republic of Haiti','Port-au-Prince','Americas'),
        ('Honduras','HN','HND',340,'Republic of Honduras','Tegucigalpa','Americas'),
        ('Hungary','HU','HUN',348,'Hungary','Budapest','EU'),
        ('Iceland','IS','ISL',352,'Iceland','Reykjavik','EEA'),
        ('India','IN','IND',356,'Republic of India','New Delhi','Asia-Pacific'),
        ('Indonesia','ID','IDN',360,'Republic of Indonesia','Jakarta','Asia-Pacific'),
        ('Iran','IR','IRN',364,'Islamic Republic of Iran','Tehran','MENA'),
        ('Iraq','IQ','IRQ',368,'Republic of Iraq','Baghdad','MENA'),
        ('Ireland','IE','IRL',372,'Ireland','Dublin','EU'),
        ('Israel','IL','ISR',376,'State of Israel','Jerusalem','MENA'),
        ('Italy','IT','ITA',380,'Italian Republic','Rome','EU'),
        ('Ivory Coast','CI','CIV',384,'Republic of Cote d''Ivoire','Yamoussoukro','SSA'),
        ('Jamaica','JM','JAM',388,'Jamaica','Kingston','Americas'),
        ('Japan','JP','JPN',392,'Japan','Tokyo','Asia-Pacific'),
        ('Jordan','JO','JOR',400,'Hashemite Kingdom of Jordan','Amman','MENA'),
        ('Kazakhstan','KZ','KAZ',398,'Republic of Kazakhstan','Astana','Asia-Pacific'),
        ('Kenya','KE','KEN',404,'Republic of Kenya','Nairobi','SSA'),
        ('Kiribati','KI','KIR',296,'Republic of Kiribati','Tarawa','Asia-Pacific'),
        ('Kosovo','XK','XKX',NULL,'Republic of Kosovo','Pristina','Europe'),
        ('Kuwait','KW','KWT',414,'State of Kuwait','Kuwait City','MENA'),
        ('Kyrgyzstan','KG','KGZ',417,'Kyrgyz Republic','Bishkek','Asia-Pacific'),
        ('Laos','LA','LAO',418,'Lao People''s Democratic Republic','Vientiane','Asia-Pacific'),
        ('Latvia','LV','LVA',428,'Republic of Latvia','Riga','EU'),
        ('Lebanon','LB','LBN',422,'Lebanese Republic','Beirut','MENA'),
        ('Lesotho','LS','LSO',426,'Kingdom of Lesotho','Maseru','SSA'),
        ('Liberia','LR','LBR',430,'Republic of Liberia','Monrovia','SSA'),
        ('Libya','LY','LBY',434,'State of Libya','Tripoli','MENA'),
        ('Liechtenstein','LI','LIE',438,'Principality of Liechtenstein','Vaduz','EEA'),
        ('Lithuania','LT','LTU',440,'Republic of Lithuania','Vilnius','EU'),
        ('Luxembourg','LU','LUX',442,'Grand Duchy of Luxembourg','Luxembourg','EU'),
        ('Madagascar','MG','MDG',450,'Republic of Madagascar','Antananarivo','SSA'),
        ('Malawi','MW','MWI',454,'Republic of Malawi','Lilongwe','SSA'),
        ('Malaysia','MY','MYS',458,'Malaysia','Kuala Lumpur','Asia-Pacific'),
        ('Maldives','MV','MDV',462,'Republic of Maldives','Male','Asia-Pacific'),
        ('Mali','ML','MLI',466,'Republic of Mali','Bamako','SSA'),
        ('Malta','MT','MLT',470,'Republic of Malta','Valletta','EU'),
        ('Marshall Islands','MH','MHL',584,'Republic of the Marshall Islands','Majuro','Asia-Pacific'),
        ('Mauritania','MR','MRT',478,'Islamic Republic of Mauritania','Nouakchott','SSA'),
        ('Mauritius','MU','MUS',480,'Republic of Mauritius','Port Louis','SSA'),
        ('Mexico','MX','MEX',484,'United Mexican States','Mexico City','Americas'),
        ('Micronesia','FM','FSM',583,'Federated States of Micronesia','Palikir','Asia-Pacific'),
        ('Moldova','MD','MDA',498,'Republic of Moldova','Chisinau','Europe'),
        ('Monaco','MC','MCO',492,'Principality of Monaco','Monaco','Europe'),
        ('Mongolia','MN','MNG',496,'Mongolia','Ulaanbaatar','Asia-Pacific'),
        ('Montenegro','ME','MNE',499,'Montenegro','Podgorica','Europe'),
        ('Morocco','MA','MAR',504,'Kingdom of Morocco','Rabat','MENA'),
        ('Mozambique','MZ','MOZ',508,'Republic of Mozambique','Maputo','SSA'),
        ('Myanmar','MM','MMR',104,'Republic of the Union of Myanmar','Naypyidaw','Asia-Pacific'),
        ('Namibia','NA','NAM',516,'Republic of Namibia','Windhoek','SSA'),
        ('Nauru','NR','NRU',520,'Republic of Nauru','Yaren','Asia-Pacific'),
        ('Nepal','NP','NPL',524,'Federal Democratic Republic of Nepal','Kathmandu','Asia-Pacific'),
        ('Netherlands','NL','NLD',528,'Kingdom of the Netherlands','Amsterdam','EU'),
        ('New Caledonia','NC','NCL',540,'New Caledonia','Noumea','Asia-Pacific'),
        ('New Zealand','NZ','NZL',554,'New Zealand','Wellington','Asia-Pacific'),
        ('Nicaragua','NI','NIC',558,'Republic of Nicaragua','Managua','Americas'),
        ('Niger','NE','NER',562,'Republic of Niger','Niamey','SSA'),
        ('Nigeria','NG','NGA',566,'Federal Republic of Nigeria','Abuja','SSA'),
        ('North Korea','KP','PRK',408,'Democratic People''s Republic of Korea','Pyongyang','Asia-Pacific'),
        ('North Macedonia','MK','MKD',807,'Republic of North Macedonia','Skopje','Europe'),
        ('Norway','NO','NOR',578,'Kingdom of Norway','Oslo','EEA'),
        ('Oman','OM','OMN',512,'Sultanate of Oman','Muscat','MENA'),
        ('Pakistan','PK','PAK',586,'Islamic Republic of Pakistan','Islamabad','Asia-Pacific'),
        ('Palau','PW','PLW',585,'Republic of Palau','Ngerulmud','Asia-Pacific'),
        ('Palestine','PS','PSE',275,'State of Palestine','Ramallah','MENA'),
        ('Panama','PA','PAN',591,'Republic of Panama','Panama City','Americas'),
        ('Papua New Guinea','PG','PNG',598,'Independent State of Papua New Guinea','Port Moresby','Asia-Pacific'),
        ('Paraguay','PY','PRY',600,'Republic of Paraguay','Asuncion','Americas'),
        ('Peru','PE','PER',604,'Republic of Peru','Lima','Americas'),
        ('Philippines','PH','PHL',608,'Republic of the Philippines','Manila','Asia-Pacific'),
        ('Poland','PL','POL',616,'Republic of Poland','Warsaw','EU'),
        ('Portugal','PT','PRT',620,'Portuguese Republic','Lisbon','EU'),
        ('Qatar','QA','QAT',634,'State of Qatar','Doha','MENA'),
        ('Romania','RO','ROU',642,'Romania','Bucharest','EU'),
        ('Russia','RU','RUS',643,'Russian Federation','Moscow','Europe'),
        ('Rwanda','RW','RWA',646,'Republic of Rwanda','Kigali','SSA'),
        ('Saint Kitts and Nevis','KN','KNA',659,'Federation of Saint Christopher and Nevis','Basseterre','Americas'),
        ('Saint Lucia','LC','LCA',662,'Saint Lucia','Castries','Americas'),
        ('Saint Vincent and the Grenadines','VC','VCT',670,'Saint Vincent and the Grenadines','Kingstown','Americas'),
        ('Samoa','WS','WSM',882,'Independent State of Samoa','Apia','Asia-Pacific'),
        ('San Marino','SM','SMR',674,'Republic of San Marino','San Marino','Europe'),
        ('Sao Tome and Principe','ST','STP',678,'Democratic Republic of Sao Tome and Principe','Sao Tome','SSA'),
        ('Saudi Arabia','SA','SAU',682,'Kingdom of Saudi Arabia','Riyadh','MENA'),
        ('Senegal','SN','SEN',686,'Republic of Senegal','Dakar','SSA'),
        ('Serbia','RS','SRB',688,'Republic of Serbia','Belgrade','Europe'),
        ('Seychelles','SC','SYC',690,'Republic of Seychelles','Victoria','SSA'),
        ('Sierra Leone','SL','SLE',694,'Republic of Sierra Leone','Freetown','SSA'),
        ('Singapore','SG','SGP',702,'Republic of Singapore','Singapore','Asia-Pacific'),
        ('Slovakia','SK','SVK',703,'Slovak Republic','Bratislava','EU'),
        ('Slovenia','SI','SVN',705,'Republic of Slovenia','Ljubljana','EU'),
        ('Solomon Islands','SB','SLB',90,'Solomon Islands','Honiara','Asia-Pacific'),
        ('Somalia','SO','SOM',706,'Federal Republic of Somalia','Mogadishu','SSA'),
        ('South Africa','ZA','ZAF',710,'Republic of South Africa','Pretoria','SSA'),
        ('South Korea','KR','KOR',410,'Republic of Korea','Seoul','Asia-Pacific'),
        ('South Sudan','SS','SSD',728,'Republic of South Sudan','Juba','SSA'),
        ('Spain','ES','ESP',724,'Kingdom of Spain','Madrid','EU'),
        ('Sri Lanka','LK','LKA',144,'Democratic Socialist Republic of Sri Lanka','Colombo','Asia-Pacific'),
        ('Sudan','SD','SDN',729,'Republic of the Sudan','Khartoum','SSA'),
        ('Suriname','SR','SUR',740,'Republic of Suriname','Paramaribo','Americas'),
        ('Sweden','SE','SWE',752,'Kingdom of Sweden','Stockholm','EU'),
        ('Switzerland','CH','CHE',756,'Swiss Confederation','Bern','SEPA'),
        ('Syria','SY','SYR',760,'Syrian Arab Republic','Damascus','MENA'),
        ('Taiwan','TW','TWN',158,'Taiwan','Taipei','Asia-Pacific'),
        ('Tajikistan','TJ','TJK',762,'Republic of Tajikistan','Dushanbe','Asia-Pacific'),
        ('Tanzania','TZ','TZA',834,'United Republic of Tanzania','Dodoma','SSA'),
        ('Thailand','TH','THA',764,'Kingdom of Thailand','Bangkok','Asia-Pacific'),
        ('Timor-Leste','TL','TLS',626,'Democratic Republic of Timor-Leste','Dili','Asia-Pacific'),
        ('Togo','TG','TGO',768,'Togolese Republic','Lome','SSA'),
        ('Tonga','TO','TON',776,'Kingdom of Tonga','Nuku''alofa','Asia-Pacific'),
        ('Trinidad and Tobago','TT','TTO',780,'Republic of Trinidad and Tobago','Port of Spain','Americas'),
        ('Tunisia','TN','TUN',788,'Republic of Tunisia','Tunis','MENA'),
        ('Turkey','TR','TUR',792,'Republic of Turkiye','Ankara','MENA'),
        ('Turkmenistan','TM','TKM',795,'Turkmenistan','Ashgabat','Asia-Pacific'),
        ('Tuvalu','TV','TUV',798,'Tuvalu','Funafuti','Asia-Pacific'),
        ('Uganda','UG','UGA',800,'Republic of Uganda','Kampala','SSA'),
        ('Ukraine','UA','UKR',804,'Ukraine','Kyiv','Europe'),
        ('United Arab Emirates','AE','ARE',784,'United Arab Emirates','Abu Dhabi','MENA'),
        ('United Kingdom','GB','GBR',826,'United Kingdom of Great Britain and Northern Ireland','London','EEA'),
        ('United States','US','USA',840,'United States of America','Washington D.C.','Americas'),
        ('Uruguay','UY','URY',858,'Oriental Republic of Uruguay','Montevideo','Americas'),
        ('Uzbekistan','UZ','UZB',860,'Republic of Uzbekistan','Tashkent','Asia-Pacific'),
        ('Vanuatu','VU','VUT',548,'Republic of Vanuatu','Port Vila','Asia-Pacific'),
        ('Vatican City','VA','VAT',336,'Vatican City State','Vatican City','Europe'),
        ('Venezuela','VE','VEN',862,'Bolivarian Republic of Venezuela','Caracas','Americas'),
        ('Vietnam','VN','VNM',704,'Socialist Republic of Vietnam','Hanoi','Asia-Pacific'),
        ('Wallis and Futuna','WF','WLF',876,'Wallis and Futuna','Mata-Utu','Asia-Pacific'),
        ('Yemen','YE','YEM',887,'Republic of Yemen','Sanaa','MENA'),
        ('Zambia','ZM','ZMB',894,'Republic of Zambia','Lusaka','SSA'),
        ('Zimbabwe','ZW','ZWE',716,'Republic of Zimbabwe','Harare','SSA')
      ON CONFLICT (iso2) DO NOTHING
    `);

    await client.query(`
      INSERT INTO geo_currencies (code, name, symbol, minor_units)
      VALUES
        ('AED','United Arab Emirates Dirham','د.إ',2),
        ('AFN','Afghan Afghani','؋',2),
        ('ALL','Albanian Lek','L',2),
        ('AMD','Armenian Dram','֏',2),
        ('ANG','Netherlands Antillean Guilder','ƒ',2),
        ('AOA','Angolan Kwanza','Kz',2),
        ('ARS','Argentine Peso','$',2),
        ('AUD','Australian Dollar','A$',2),
        ('AWG','Aruban Florin','ƒ',2),
        ('AZN','Azerbaijani Manat','₼',2),
        ('BAM','Bosnia-Herzegovina Convertible Mark','KM',2),
        ('BBD','Barbadian Dollar','Bds$',2),
        ('BDT','Bangladeshi Taka','৳',2),
        ('BGN','Bulgarian Lev','лв',2),
        ('BHD','Bahraini Dinar','BD',3),
        ('BIF','Burundian Franc','FBu',0),
        ('BMD','Bermudian Dollar','$',2),
        ('BND','Brunei Dollar','B$',2),
        ('BOB','Bolivian Boliviano','Bs.',2),
        ('BRL','Brazilian Real','R$',2),
        ('BSD','Bahamian Dollar','B$',2),
        ('BTN','Bhutanese Ngultrum','Nu.',2),
        ('BWP','Botswana Pula','P',2),
        ('BYN','Belarusian Ruble','Br',2),
        ('BZD','Belize Dollar','BZ$',2),
        ('CAD','Canadian Dollar','C$',2),
        ('CDF','Congolese Franc','FC',2),
        ('CHF','Swiss Franc','CHF',2),
        ('CLP','Chilean Peso','$',0),
        ('CNY','Chinese Yuan','¥',2),
        ('COP','Colombian Peso','$',2),
        ('CRC','Costa Rican Colon','₡',2),
        ('CUP','Cuban Peso','$',2),
        ('CVE','Cape Verdean Escudo','$',2),
        ('CZK','Czech Koruna','Kč',2),
        ('DJF','Djiboutian Franc','Fdj',0),
        ('DKK','Danish Krone','kr',2),
        ('DOP','Dominican Peso','RD$',2),
        ('DZD','Algerian Dinar','د.ج',2),
        ('EGP','Egyptian Pound','E£',2),
        ('ERN','Eritrean Nakfa','Nfk',2),
        ('ETB','Ethiopian Birr','Br',2),
        ('EUR','Euro','€',2),
        ('FJD','Fijian Dollar','FJ$',2),
        ('FKP','Falkland Islands Pound','£',2),
        ('GBP','British Pound Sterling','£',2),
        ('GEL','Georgian Lari','₾',2),
        ('GHS','Ghanaian Cedi','GH₵',2),
        ('GIP','Gibraltar Pound','£',2),
        ('GMD','Gambian Dalasi','D',2),
        ('GNF','Guinean Franc','FG',0),
        ('GTQ','Guatemalan Quetzal','Q',2),
        ('GYD','Guyanese Dollar','G$',2),
        ('HKD','Hong Kong Dollar','HK$',2),
        ('HNL','Honduran Lempira','L',2),
        ('HRK','Croatian Kuna','kn',2),
        ('HTG','Haitian Gourde','G',2),
        ('HUF','Hungarian Forint','Ft',2),
        ('IDR','Indonesian Rupiah','Rp',2),
        ('ILS','Israeli New Shekel','₪',2),
        ('INR','Indian Rupee','₹',2),
        ('IQD','Iraqi Dinar','ع.د',3),
        ('IRR','Iranian Rial','﷼',2),
        ('ISK','Icelandic Krona','kr',0),
        ('JMD','Jamaican Dollar','J$',2),
        ('JOD','Jordanian Dinar','JD',3),
        ('JPY','Japanese Yen','¥',0),
        ('KES','Kenyan Shilling','KSh',2),
        ('KGS','Kyrgyzstani Som','сом',2),
        ('KHR','Cambodian Riel','៛',2),
        ('KMF','Comorian Franc','CF',0),
        ('KPW','North Korean Won','₩',2),
        ('KRW','South Korean Won','₩',0),
        ('KWD','Kuwaiti Dinar','KD',3),
        ('KYD','Cayman Islands Dollar','CI$',2),
        ('KZT','Kazakhstani Tenge','₸',2),
        ('LAK','Lao Kip','₭',2),
        ('LBP','Lebanese Pound','L£',2),
        ('LKR','Sri Lankan Rupee','Rs',2),
        ('LRD','Liberian Dollar','L$',2),
        ('LSL','Lesotho Loti','L',2),
        ('LYD','Libyan Dinar','LD',3),
        ('MAD','Moroccan Dirham','MAD',2),
        ('MDL','Moldovan Leu','L',2),
        ('MGA','Malagasy Ariary','Ar',2),
        ('MKD','Macedonian Denar','ден',2),
        ('MMK','Myanmar Kyat','K',2),
        ('MNT','Mongolian Tugrik','₮',2),
        ('MOP','Macanese Pataca','MOP$',2),
        ('MRU','Mauritanian Ouguiya','UM',2),
        ('MUR','Mauritian Rupee','Rs',2),
        ('MVR','Maldivian Rufiyaa','Rf',2),
        ('MWK','Malawian Kwacha','MK',2),
        ('MXN','Mexican Peso','Mex$',2),
        ('MYR','Malaysian Ringgit','RM',2),
        ('MZN','Mozambican Metical','MT',2),
        ('NAD','Namibian Dollar','N$',2),
        ('NGN','Nigerian Naira','₦',2),
        ('NIO','Nicaraguan Cordoba','C$',2),
        ('NOK','Norwegian Krone','kr',2),
        ('NPR','Nepalese Rupee','Rs',2),
        ('NZD','New Zealand Dollar','NZ$',2),
        ('OMR','Omani Rial','OMR',3),
        ('PAB','Panamanian Balboa','B/.',2),
        ('PEN','Peruvian Sol','S/.',2),
        ('PGK','Papua New Guinean Kina','K',2),
        ('PHP','Philippine Peso','₱',2),
        ('PKR','Pakistani Rupee','Rs',2),
        ('PLN','Polish Zloty','zł',2),
        ('PYG','Paraguayan Guarani','₲',0),
        ('QAR','Qatari Riyal','QR',2),
        ('RON','Romanian Leu','lei',2),
        ('RSD','Serbian Dinar','din.',2),
        ('RUB','Russian Ruble','₽',2),
        ('RWF','Rwandan Franc','RF',0),
        ('SAR','Saudi Riyal','SAR',2),
        ('SBD','Solomon Islands Dollar','SI$',2),
        ('SCR','Seychellois Rupee','Rs',2),
        ('SDG','Sudanese Pound','SDG',2),
        ('SEK','Swedish Krona','kr',2),
        ('SGD','Singapore Dollar','S$',2),
        ('SHP','Saint Helena Pound','£',2),
        ('SLE','Sierra Leonean Leone','Le',2),
        ('SOS','Somali Shilling','Sh',2),
        ('SRD','Surinamese Dollar','$',2),
        ('SSP','South Sudanese Pound','SS£',2),
        ('STN','Sao Tome and Principe Dobra','Db',2),
        ('SYP','Syrian Pound','£S',2),
        ('SZL','Eswatini Lilangeni','E',2),
        ('THB','Thai Baht','฿',2),
        ('TJS','Tajikistani Somoni','SM',2),
        ('TMT','Turkmenistani Manat','T',2),
        ('TND','Tunisian Dinar','DT',3),
        ('TOP','Tongan Pa''anga','T$',2),
        ('TRY','Turkish Lira','₺',2),
        ('TTD','Trinidad and Tobago Dollar','TT$',2),
        ('TWD','New Taiwan Dollar','NT$',2),
        ('TZS','Tanzanian Shilling','TSh',2),
        ('UAH','Ukrainian Hryvnia','₴',2),
        ('UGX','Ugandan Shilling','USh',0),
        ('USD','United States Dollar','$',2),
        ('UYU','Uruguayan Peso','$U',2),
        ('UZS','Uzbekistani Som','soʻm',2),
        ('VES','Venezuelan Bolivar Soberano','Bs.S',2),
        ('VND','Vietnamese Dong','₫',0),
        ('VUV','Vanuatu Vatu','VT',0),
        ('WST','Samoan Tala','WS$',2),
        ('XAF','Central African CFA Franc','FCFA',0),
        ('XCD','Eastern Caribbean Dollar','EC$',2),
        ('XOF','West African CFA Franc','CFA',0),
        ('XPF','CFP Franc','F',0),
        ('YER','Yemeni Rial','﷼',2),
        ('ZAR','South African Rand','R',2),
        ('ZMW','Zambian Kwacha','ZK',2),
        ('ZWL','Zimbabwean Dollar','Z$',2)
      ON CONFLICT (code) DO NOTHING
    `);

    const primaryLinks: [string, string][] = [
      ['AF','AFN'],['AL','ALL'],['DZ','DZD'],['AD','EUR'],['AO','AOA'],
      ['AG','XCD'],['AR','ARS'],['AM','AMD'],['AU','AUD'],['AT','EUR'],
      ['AZ','AZN'],['BS','BSD'],['BH','BHD'],['BD','BDT'],['BB','BBD'],
      ['BY','BYN'],['BE','EUR'],['BZ','BZD'],['BJ','XOF'],['BT','BTN'],
      ['BO','BOB'],['BA','BAM'],['BW','BWP'],['BR','BRL'],['BN','BND'],
      ['BG','BGN'],['BF','XOF'],['BI','BIF'],['CV','CVE'],['KH','KHR'],
      ['CM','XAF'],['CA','CAD'],['CF','XAF'],['TD','XAF'],['CL','CLP'],
      ['CN','CNY'],['CO','COP'],['KM','KMF'],['CG','XAF'],['CD','CDF'],
      ['CR','CRC'],['HR','EUR'],['CU','CUP'],['CY','EUR'],['CZ','CZK'],
      ['DK','DKK'],['DJ','DJF'],['DM','XCD'],['DO','DOP'],['EC','USD'],
      ['EG','EGP'],['SV','USD'],['GQ','XAF'],['ER','ERN'],['EE','EUR'],
      ['SZ','SZL'],['ET','ETB'],['FJ','FJD'],['FI','EUR'],['FR','EUR'],
      ['PF','XPF'],
      ['GA','XAF'],['GM','GMD'],['GE','GEL'],['DE','EUR'],['GH','GHS'],
      ['GR','EUR'],['GD','XCD'],['GT','GTQ'],['GN','GNF'],['GW','XOF'],
      ['GY','GYD'],['HT','HTG'],['HN','HNL'],['HU','HUF'],['IS','ISK'],
      ['IN','INR'],['ID','IDR'],['IR','IRR'],['IQ','IQD'],['IE','EUR'],
      ['IL','ILS'],['IT','EUR'],['CI','XOF'],['JM','JMD'],['JP','JPY'],
      ['JO','JOD'],['KZ','KZT'],['KE','KES'],['KI','AUD'],['XK','EUR'],
      ['KW','KWD'],['KG','KGS'],['LA','LAK'],['LV','EUR'],['LB','LBP'],
      ['LS','LSL'],['LR','LRD'],['LY','LYD'],['LI','CHF'],['LT','EUR'],
      ['LU','EUR'],['MG','MGA'],['MW','MWK'],['MY','MYR'],['MV','MVR'],
      ['ML','XOF'],['MT','EUR'],['MH','USD'],['MR','MRU'],['MU','MUR'],
      ['MX','MXN'],['FM','USD'],['MD','MDL'],['MC','EUR'],['MN','MNT'],
      ['ME','EUR'],['MA','MAD'],['MZ','MZN'],['MM','MMK'],['NA','NAD'],
      ['NR','AUD'],['NP','NPR'],['NL','EUR'],
      ['NC','XPF'],
      ['NZ','NZD'],['NI','NIO'],
      ['NE','XOF'],['NG','NGN'],['KP','KPW'],['MK','MKD'],['NO','NOK'],
      ['OM','OMR'],['PK','PKR'],['PW','USD'],['PS','ILS'],['PA','PAB'],
      ['PG','PGK'],['PY','PYG'],['PE','PEN'],['PH','PHP'],['PL','PLN'],
      ['PT','EUR'],['QA','QAR'],['RO','RON'],['RU','RUB'],['RW','RWF'],
      ['KN','XCD'],['LC','XCD'],['VC','XCD'],['WS','WST'],['SM','EUR'],
      ['ST','STN'],['SA','SAR'],['SN','XOF'],['RS','RSD'],['SC','SCR'],
      ['SL','SLE'],['SG','SGD'],['SK','EUR'],['SI','EUR'],['SB','SBD'],
      ['SO','SOS'],['ZA','ZAR'],['KR','KRW'],['SS','SSP'],['ES','EUR'],
      ['LK','LKR'],['SD','SDG'],['SR','SRD'],['SE','SEK'],['CH','CHF'],
      ['SY','SYP'],['TW','TWD'],['TJ','TJS'],['TZ','TZS'],['TH','THB'],
      ['TL','USD'],['TG','XOF'],['TO','TOP'],['TT','TTD'],['TN','TND'],
      ['TR','TRY'],['TM','TMT'],['TV','AUD'],['UG','UGX'],['UA','UAH'],
      ['AE','AED'],['GB','GBP'],['US','USD'],['UY','UYU'],['UZ','UZS'],
      ['VU','VUV'],['VA','EUR'],['VE','VES'],['VN','VND'],
      ['WF','XPF'],
      ['YE','YER'],
      ['ZM','ZMW'],['ZW','ZWL']
    ];

    for (const [iso2, currCode] of primaryLinks) {
      await client.query(`
        INSERT INTO country_currencies (country_id, currency_id, is_primary)
        SELECT c.id, cur.id, true
        FROM countries c, geo_currencies cur
        WHERE c.iso2 = $1 AND cur.code = $2
          AND NOT EXISTS (
            SELECT 1 FROM country_currencies cc
            WHERE cc.country_id = c.id AND cc.currency_id = cur.id
          )
      `, [iso2, currCode]);
    }

    const secondaryLinks: [string, string][] = [
      ['BT','INR'],['LS','ZAR'],['NA','ZAR'],['PA','USD'],['SZ','ZAR']
    ];
    for (const [iso2, currCode] of secondaryLinks) {
      await client.query(`
        INSERT INTO country_currencies (country_id, currency_id, is_primary)
        SELECT c.id, cur.id, false
        FROM countries c, geo_currencies cur
        WHERE c.iso2 = $1 AND cur.code = $2
          AND NOT EXISTS (
            SELECT 1 FROM country_currencies cc
            WHERE cc.country_id = c.id AND cc.currency_id = cur.id
          )
      `, [iso2, currCode]);
    }

    await client.query("COMMIT");

    const counts = await client.query(`
      SELECT
        (SELECT count(*) FROM countries) AS countries,
        (SELECT count(*) FROM geo_currencies) AS currencies,
        (SELECT count(*) FROM country_currencies) AS links
    `);
    const r = counts.rows[0];
    console.log(`[GeoSeed] ${r.countries} countries, ${r.currencies} currencies, ${r.links} links seeded.`);
  } catch (err) {
    await client.query("ROLLBACK");
    console.error("[GeoSeed] Bootstrap error (non-fatal):", (err as Error).message);
  } finally {
    client.release();
  }
}
